export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const FETCH_USER_ABOUT = 'FETCH_USER_ABOUT';
export const FETCH_USER_INTEREST = 'FETCH_USER_INTEREST';
export const UPDATE_USER_ABOUT = 'UPDATE_USER_ABOUT';
export const UPDATE_USER_INTEREST = 'UPDATE_USER_INTEREST';

export const FETCH_LISTING = 'FETCH_LISTING';
export const FETCH_FILES = 'FETCH_FILES';
export const ADD_NEW_FILE = 'ADD_NEW_FILE';
export const STAR_FILE = 'STAR_FILE';
export const DELETE_FILE = 'DELETE_FILE';

export const FETCH_FOLDERS = 'FETCH_FOLDERS';
export const ADD_NEW_FOLDER = 'ADD_NEW_FOLDER';
export const STAR_FOLDER = 'STAR_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';

export const FETCH_CONTENTS_BY_FOLDER_ID = 'FETCH_CONTENTS_BY_FOLDER_ID';

// Navigation Breadcrumb
export const BREADCRUMB_PUSH = 'BREADCRUMB_PUSH';
export const BREADCRUMB_POP = 'BREADCRUMB_POP';
export const BREADCRUMB_CLEAR = 'BREADCRUMB_CLEAR';

// Sharing
export const FILE_SHARING_ADD = 'FILE_SHARING_ADD';
export const FILE_SHARING_REMOVE = 'FILE_SHARING_REMOVE';
export const FETCH_SHARE_FILES = 'FETCH_SHARE_FILES';

export const FOLDER_SHARING_ADD = 'FOLDER_SHARING_ADD';
export const FOLDER_SHARING_REMOVE = 'FOLDER_SHARING_REMOVE';
export const FETCH_SHARE_FOLDERS = 'FETCH_SHARE_FOLDERS';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const SIGN_IN_ERROR_CLEAR = 'SIGN_IN_ERROR_CLEAR';
export const SIGN_UP_ERROR_CLEAR = 'SIGN_UP_ERROR_CLEAR';
export const SIGN_UP_SUCCESS_CLEAR = 'SIGN_UP_SUCCESS_CLEAR';
